config/routes.rb
Rails.application.routes.draw do


  get 'accounts/new'
  get 'accounts/create'
  get 'new/create'


  ## Resources and routes for admin sessions  and admin user creation##
  resources :admin_users , only: [:new,:create]


  get 'admin', to:'admin_sessions#adminPage'
  get 'admin/login', to: 'admin_sessions#new'
  post 'admin/login',to:'admin_sessions#create'
  get 'admin/logout', to: 'admin_sessions#adminLogout'
  get 'admin/panel' , to: 'admin_sessions#adminPanel'

 ## Resources for user controller with inside the admin pages ##
  resources :user , only: [:new,:create], :path =>'admin/panel/user'
  get 'admin/panel/user/new', :to => 'user1#new', :as => :user
  post 'admin/panel/user/delete', :to => 'user#delete'
  get 'admin/panel/user/:id', to: 'user#show'

## Resources for accounts for user controller inside the admin pages ###
  get '/accounts/new' ,to: 'accounts#new'
  post '/accounts/create', to:'accounts#create'
  get  '/admin/panel/user/:id/:account_id', to:'accounts#admin_view'
  get '/admin/panel/user/:id/:account_id/delete', :to => "accounts#delete"

  # Resources for transactions inside the admin pages
 post '/admin/panel/user/:id/:account_id/create', to:"transactions#create"
 get '/admin/panel/user/:id/:account_id/:transaction_id/delete', to: "transactions#delete"

## resources for managing the main UI ##
  root 'sessions#new'
 
  resources :visitors
  
  get 'visitors/:account_id/transactions', to:'visitors#transactions'
  get 'visitors/:account_id/new_transaction', to:'visitors#new_transaction'
  post 'visitors/:account_id/create_transaction', to:'visitors#create_new_transaction'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/admin_sessions_controller.rb
class AdminSessionsController < ApplicationController
   before_action:redirect_to_admin_if_not_logged_in, only: [:adminPanel]

  def new
  end

  def create
    @admin_user = AdminUser.find_by(username: params[:username])
    if @admin_user && @admin_user.authenticate(params[:password])
       session[:admin_id] = @admin_user.id
       redirect_to '/admin/panel'
    else
      redirect_to'/admin'
    end
 end

  def adminLogin
  end

  def adminPage
      if helpers.admin_logged_in?
         redirect_to '/admin/panel'
      end
  end

  def adminLogout
   if helpers.admin_logged_in?
      session.delete(:admin_id)
   end
   redirect_to '/admin'
  end
  def adminPanel
    @site_users = User1.find_each
  end
  private 
    def redirect_to_admin_if_not_logged_in
      if !helpers.admin_logged_in?
         redirect_to '/admin'
      end
   end

end

app/helpers/admin_sessions_helper.rb
module AdminSessionsHelper
    def hasAdminUser
        AdminUser.any? 
    end
    def current_admin_user
        AdminUser.find_by(id: session[:admin_id])
    end


    def admin_logged_in?
        !current_admin_user.nil?
    end
end

app/views/admin_sessions/_admin_show_users.html.erb
<div class="usersList">
  <h2>Site Users</h2>
  <table class="listing" >
    <tr class="header">
      <th>Username</th>
      <th>Number of Accounts</th>
      <th > Created at </th>
    </tr>
    <% @site_users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.accounts.all.count%></td>
      <td><%= user.created_at%> </td>
      <td class="actions">
      <td><%= button_to 'Delete', {:controller => "user", :action => "delete", :user_id => user.id, :method=>:post}  %></td>
      </td>
      <td> <%= button_to "View/Edit", 'panel/user/'+user.id.to_s , :method => "get" %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/admin_sessions/adminPage.html.erb
<% if admin_logged_in? %>
    <h1>You are Logged In, <%= current_admin_user.username %></h1>
    <%= button_to "Logout", '/admin/logout', method: :get%>
    
<%else%>
<%= bootstrap_form_with(url: 'admin/login') do |f| %>
   <%= f.text_field :username %>
   <%= f.password_field :password %>
   <%= f.submit "Log in", class: 'btn btn-primary' %>
<% end %>
<%if !hasAdminUser%>
    <%= button_to "Create First Admin", '/admin_users/new', method: :get%>
<%end%>
<%end%>

app/views/admin_sessions/adminPanel.html.erb
<h1>Admin Panel</h1>

<h2>Welcome to the admin panel  <%= current_admin_user.username %></h2>
<%= button_to "Logout", '/admin/logout', method: :get%>
<%= button_to "Create New Admin User", '/admin_users/new', method: :get%>
<%= button_to "Create New Normal User", new_user_url, method: :get%>
<%= render 'admin_show_users'%>

app/views/admin_sessions/create.html.erb
<h1>AdminSessions#create</h1>
<p>Find me in app/views/admin_sessions/create.html.erb</p>

app/views/admin_sessions/login.html.erb
<h1>AdminSessions#login</h1>
<p>Find me in app/views/admin_sessions/login.html.erb</p>
#might need to change this to admin_login or it will conflict with the standard bank login page

app/views/admin_sessions/new.html.erb
<h1>Admin Login</h1>
   <%= form_tag '/login' do %>
   <%= label_tag :username%>
   <%= text_field_tag :username %>
   <%= label_tag :password%>
   <%= password_field_tag :password%>
   <%= submit_tag "Login"%>
<%end%>