config/routes.rb
Rails.application.routes.draw do


  get 'accounts/new'
  get 'accounts/create'
  get 'new/create'


  ## Resources and routes for admin sessions  and admin user creation##
  resources :admin_users , only: [:new,:create]


  get 'admin', to:'admin_sessions#adminPage'
  get 'admin/login', to: 'admin_sessions#new'
  post 'admin/login',to:'admin_sessions#create'
  get 'admin/logout', to: 'admin_sessions#adminLogout'
  get 'admin/panel' , to: 'admin_sessions#adminPanel'

 ## Resources for user controller with inside the admin pages ##
  resources :user , only: [:new,:create], :path =>'admin/panel/user'
  get 'admin/panel/user/new', :to => 'user1#new', :as => :user
  post 'admin/panel/user/delete', :to => 'user#delete'
  get 'admin/panel/user/:id', to: 'user#show'

## Resources for accounts for user controller inside the admin pages ###
  get '/accounts/new' ,to: 'accounts#new'
  post '/accounts/create', to:'accounts#create'
  get  '/admin/panel/user/:id/:account_id', to:'accounts#admin_view'
  get '/admin/panel/user/:id/:account_id/delete', :to => "accounts#delete"

  # Resources for transactions inside the admin pages
 post '/admin/panel/user/:id/:account_id/create', to:"transactions#create"
 get '/admin/panel/user/:id/:account_id/:transaction_id/delete', to: "transactions#delete"

## resources for managing the main UI ##
  root 'sessions#new'
 
  resources :visitors
  
  get 'visitors/:account_id/transactions', to:'visitors#transactions'
  get 'visitors/:account_id/new_transaction', to:'visitors#new_transaction'
  post 'visitors/:account_id/create_transaction', to:'visitors#create_new_transaction'


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#logout'






  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    before_action:redirect_to_admin_if_not_logged_in
   
    def new
        @user = User1.new  
    end
    
    def create
        @user = User1.create(params.require(:user1).permit(:username,:password))
        redirect_to '/admin/panel'
    end

    def delete
        @accounts = Account.where(user1_id: params[:user_id]) # get accounts for this user
        @accounts.each do |a|                                 # for account belonging to this user delete all the transactions
            Transaction.where(account_id: a.id).destroy_all
         end
        @accounts.destroy_all                                 # delete all the accounts
        User1.find(params[:user_id]).destroy;                 # delete the user
        redirect_to  '/admin/panel'
      
    end
    
    def show
        @user = User1.find(params[:id])
  
    end
 
    private 
    def redirect_to_admin_if_not_logged_in
       if !helpers.admin_logged_in?
          redirect_to '/admin'
      end
    end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/user/create.html.erb
<h1>AdminUsers#create</h1>
<p>Find me in app/views/admin_users/create.html.erb</p>

app/views/user/new.html.erb
<h1>Define a new Site User</h1>
<%= form_for(@user, url: user_index_url) do |f|%>
  <%= f.label :username%><br>
  <%= f.text_field :username%><br>
  <%= f.label :password%><br>
  <%= f.password_field :password,:minlength => 6%><br>
  <%= f.submit %>
<%end%>

app/views/user/show.html.erb
<h1>Create a new Account</h1>


<%= form_with model: Account.new,:url => url_for(:controller => 'accounts', :action => 'create'), method: :post do|f| %>
  <%= f.label :account_number%>
  <%= f.text_field :account_number%>
  <%= f.label :amount%>
  <%= f.number_field :amount%>
  <%= f.label :currency %>
  <%= f.select :currency, [ '£','€','$' ] %>
  <%= f.hidden_field :user1_id, :value => @user.id %>
  <%= f.submit %>
<% end %>
<h2> <%= @user.username + "'s accounts" %>
    <%accounts = @user.accounts.all %>
    <div class="row">
     <% accounts.each do |acc| %>

      <div class="column">
        <h2>Account Number : <%= acc.account_number %></h2>
        <p>Your balance is:<%= "#{acc.currency}#{acc.amount}"%><br></p>
        <%= button_to "View/Edit", @user.id.to_s + "/" +acc.id.to_s, :method => "get" %>
        <%= button_to 'Delete',@user.id.to_s + "/" +acc.id.to_s + "/delete" , :method=> "get"  %>
        <td></td>
      </div>
       <%end %>
    </div>